name: Are dev settings synced?

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: docker run -t -v ${PWD}/:/mnt/ ianstorm/dev-settings-sync check
